language: java

before_install:
  â€“ ./gradlew build

jdk:
  - openjdk11

script:
  - sonar-scanner

git:
  depth: false

services:
  - mongodb

addons:
  sonarcloud:
    organization: "arturarede"
    token: 5c67909bc9dac35fcaba891b436a874a91d2c122